Fix Patch
I need this change for the "Patch" method to work.  I am using php 8.1.

You can see that CURLOPT_PATCH doesn't exist in the docs here: https://www.php.net/manual/en/function.curl-setopt.php

With the code as is, I get this error because CURLOPT_PATCH isn't a constant:
```
Error: Undefined constant "PHPLicengine\Api\CURLOPT_PATCH"
```